### ISSUE TITLE
Question About Image Export Format

### ISSUE THREAD

**Issue by JOB1225** [mljar/automl-app#2]
Hi! Currently, the exported images are all in PNG format. Is it possible to export them in an editable format such as PDF? Thanks for your help.

**Comment by JOB1225** [comment]
I used the AutoML app for model training and generated some results, as shown in the figure, which includes many images, for example, roc_curve.png. However, I hope that these generated images can be in an editable format, such as SVG or PDF.![roc_curve](https://github.com/mljar/automl-app/assets/104343925/c7245e6d-f4e9-4632-a465-124a07685930)
![1](https://github.com/mljar/automl-app/assets/104343925/2d85a385-ea6a-4b17-9a2f-f872d494f81b)

**Comment by pplonski** [comment]
OK, I got you. The only solution, it to take predictions (should be saved in each model directory, file `predictions_*.csv`) and make editable image by your own based on raw data.

May I ask, what would you like to edit in the plots?

**Comment by JOB1225** [comment]
OK, thanks! I just feel that such images are too unclear and not suitable for displaying.
